version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Publish Crate
          command: |
            if [ $CIRCLE_BRANCH == master ]; then cargo login $CARGO_TOKEN && cargo package --allow-dirty && cargo publish --allow-dirty; fi
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
